%% PLOT HIGHEST PERFORMING 


% POPULATION SIZE
POPULATION_SIZE = 400;


% LOAD DATA
load('ANALYSIS.mat');
load('RESULTS.mat');
INDEX = ANALYSIS.TYPE6.INDEX_LOW_MAKE;
POPULATION = UNIVERSE(INDEX).POPULATION;


% PREALLOCATION OF OBJECTS
x = zeros(POPULATION_SIZE, 1, 'double');
y = zeros(POPULATION_SIZE, 1, 'double');
z = zeros(POPULATION_SIZE, 1, 'double');

% VARIABLES FOR LOWEST & HIGHEST CON SWIT TIME
HIGHEST_CON_SWIT_TIME = 0;
LOWEST_CON_SWITCH_TIME = 40000;


i = 1;
while i <= POPULATION_SIZE
    x(i) = POPULATION(i).TOTAL_MAKESPAN_TIME;
	y(i) = POPULATION(i).TOTAL_PROCESSING_TIME;
    z(i) = POPULATION(i).TOTAL_CON_SWIT_TIME;
    
    % FIND HIGHEST & LOWEST CON_SWIT_TIME
    if POPULATION(i).TOTAL_CON_SWIT_TIME > HIGHEST_CON_SWIT_TIME
        HIGHEST_CON_SWIT_TIME = POPULATION(i).TOTAL_CON_SWIT_TIME;
    end
    if  POPULATION(i).TOTAL_CON_SWIT_TIME < LOWEST_CON_SWITCH_TIME
        LOWEST_CON_SWITCH_TIME = POPULATION(i).TOTAL_CON_SWIT_TIME;
    end
    
    % INCREMENT
    i = i + 1;
end

% PLOT
s = scatter(x,y,[],z,'filled');
colormap(jet(10))
s.SizeData = 60;
s.MarkerEdgeColor = [0 0 0];
s.LineWidth = 1;
%colorbar;
hcb=colorbar;
hcb.Title.String = "Context Switching Time";
hold on

% MEAN
MEAN_MAKESPAN = mean(x);
MEAN_PROCTIME = mean(y);
save('MEAN_MAKESPAN.mat','MEAN_MAKESPAN');
save('MEAN_PROCTIME.mat','MEAN_PROCTIME');
STD_MAKESPAN = std(x);
STD_PROCTIME = std(y);
save('STD_MAKESPAN.mat','STD_MAKESPAN');
save('STD_PROCTIME.mat','STD_PROCTIME');

% LINEAR REGRESSION
b1 = x\y;
yCalc1 = b1*x;
plot(x,yCalc1,'LineWidth',1,'Color',[0,0,0]);

% TITLES & LABELS
title('PLOT OF INDIVIDUALS IN CONFIGURATION - [ 2 0 0 3 1 ]')
ylabel('TOTAL PROCESSING TIME');
xlabel('TOTAL MAKESPAN TIME');
legend('INDIVIDUAL','LINEAR FIT');

% OTHER 
grid on
grid minor 
ylim([200000 210000]);
xlim([34000 40000]);
